language: node_js

node_js:
  - '0.10'

git:
  depth: 1

before_install:
  - gem update --system
  - gem install sass --version "3.3.3" --no-document
  - gem install compass --version "1.0.0.alpha.19" --no-document
  - gem install tilt  --version "1.3.0" --no-document

before_script:
  - chmod +x .travis/after_success.sh
  - chmod +x ./deploy

script:
  - npm test

branches:
  except:
    - gh-pages
    - develop

env:
  global:
    - REPO="git@github.com:code4hk/code4hk.github.io"
    - secure: "ADV2ZFaB9GtXPyrDwSnQ+DfEaVtG6zlAm4Tp5H5scFjSZ+DQg4UmjFP9d5ioLkf1n/DsCaOMPE/aLL1JitHfl4o4KcabP+y8Tmm0+69fX/1YEadFliU1P5PkAhS/w1Jh44hgBePqqlO8tkkAJ1ENneQMABpRz0ibVVmuX1QZpBs="

after_success: .travis/after_success.sh
