language: node_js

node_js:
  - '0.10'

git:
  depth: 1

before_install:
  - gem update --system
  - gem install sass --version "3.3.3" --no-document
  - gem install compass --version "1.0.0.alpha.19" --no-document
  - gem install tilt  --version "1.3.0" --no-document

before_script:
  - chmod +x .travis/after_success.sh
  - chmod +x ./deploy

script:
  - npm test

branches:
  except:
    - gh-pages
    - develop

env:
  global:
    - REPO="git@github.com:code4hk/code4hk.github.io"
    - secure: "NwdCBjbOteVAnQEJ9F0Gi6vppdOrNPV6jtzChaSU4+sjRtDAE1Z/Zf/yDEQ2WP9vFN0n5JXQsMycnnD1hyO+YkQBCZoKk5IIxmn4C1W+DrM2EA99wWDTIXV5FuKgqVcuq4p0oh+nQLn7A0vswYb65c6Erq3qMX3sqJtY3PyMgJc="

after_success: .travis/after_success.sh
